// <auto-generated />
namespace Finanse_aspnet_mvc.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class yco : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(yco));
        
        string IMigrationMetadata.Id
        {
            get { return "201705230952330_yco"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
